name: Clang

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '23 13 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Install dependencies
      run: sudo apt-get install clang-tools

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
          cmake -E make_directory ${{github.workspace}}/build.clang
          scan-build cmake \
             -B ${{github.workspace}}/build.clang \
             -S ${{github.workspace}} \
             -DCMAKE_BUILD_TYPE=Release
          scan-build \
             -sarif \
             -o ${{github.workspace}}/sarif \
             make \
               -C ${{github.workspace}}/build.clang \
               -j4

    - name: Upload scan-build results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{github.workspace}}/sarif
